version: '3.8'

services:
  akshat1-6:
    container_name: akshat1-6
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '8083:8080'
    volumes:
      - ./instance:/app/instance
    restart: on-failure:5
    networks:
      - bridge
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1024M'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/test
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '8081:27017'
    volumes:
      - .mongo/data:/data/db
    restart: on-failure:5
    networks:
      - bridge
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1024M'

networks:
  bridge:
    driver: bridge
