version: '3.8'

services:
  hryadyansh1-6:
    container_name: hryadyansh1-6
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '8081:8001'
    volumes:
      - ./instance:/app/instance
    restart: on-failure:5
    networks:
      - bridge
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1024M'

networks:
  bridge:
    driver: bridge
