version: '3'

services:
  finwiserf:
    container_name: finwiserf
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - "8085:80"
    depends_on:
      - finwiserb
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1024M'

  finwiserb:
    container_name: finwiserb
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "8086:5000"
    environment:
      MONGODB_URL: mongodb://mongodbfinwiser:27017/finwiser
    depends_on:
      - mongodbfinwiser
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1024M'

  mongodbfinwiser:
    container_name: mongodbfinwiser
    build:
      context: ./mongoDB
      dockerfile: Dockerfile
    volumes:
      - ./mongoDB/data:/data/db
    ports:
      - "8087:27017"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1024M'
