# Use the official MongoDB image from Docker Hub
FROM mongo

# Set environment variables
# ENV MONGO_INITDB_ROOT_USERNAME=admin
# ENV MONGO_INITDB_ROOT_PASSWORD=password

# Copy MongoDB configuration file (if needed)
# COPY mongod.conf /etc/mongod.conf

# Expose MongoDB default port
EXPOSE 27017

# Run MongoDB with authentication
CMD ["mongod"]
